package com.example.testinglearning.order;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.data.jpa.test.autoconfigure.DataJpaTest;
import org.springframework.boot.jdbc.test.autoconfigure.AutoConfigureTestDatabase;
import org.springframework.boot.jpa.test.autoconfigure.TestEntityManager;
import org.springframework.boot.testcontainers.service.connection.ServiceConnection;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.orm.ObjectOptimisticLockingFailureException;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Sort;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

import java.math.BigDecimal;
import java.time.Instant;
import java.time.temporal.ChronoUnit;
import java.util.List;
import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * Repository-slice tests for {@link OrderRepository}.
 *
 * <p>Purpose: {@link OrderRepository} is a plain Spring Data interface with no code of its own —
 * every query it runs is generated by Spring Data / Hibernate from the method name or the
 * {@code @Query} annotation. There is nothing to unit-test in isolation; the only way to know
 * whether a derived query, a custom {@code @Query}, a unique constraint, or a cascade/orphan-
 * removal rule actually works is to run it against a real database and look at what comes back.
 * That's what these tests do (see docs/testing-strategy.md §3).
 *
 * <p>Uses a real {@code postgres:16-alpine} Testcontainer, not H2, so SQL dialect and constraint
 * behavior match production. {@code @AutoConfigureTestDatabase(Replace.NONE)} stops Spring Boot
 * from swapping the container out for an embedded database. Each test method runs in its own
 * transaction that {@code @DataJpaTest} rolls back afterwards, so tests don't need to clean up
 * after themselves or worry about execution order.
 */
@DataJpaTest
@Testcontainers
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
class OrderRepositorySliceTest {

    @Container
    @ServiceConnection
    static final PostgreSQLContainer<?> postgres = new PostgreSQLContainer<>("postgres:16-alpine");

    @Autowired
    private OrderRepository orderRepository;

    @Autowired
    private TestEntityManager entityManager;

    @Test
    void findByOrderNumber_whenOrderExists_returnsIt() {
        orderRepository.save(new Order("ORD-1", "alice@example.com", Instant.now()));

        Optional<Order> found = orderRepository.findByOrderNumber("ORD-1");

        assertThat(found).isPresent();
        assertThat(found.get().getCustomerEmail()).isEqualTo("alice@example.com");
    }

    @Test
    void findByOrderNumber_whenOrderDoesNotExist_returnsEmpty() {
        Optional<Order> found = orderRepository.findByOrderNumber("does-not-exist");

        assertThat(found).isEmpty();
    }

    @Test
    void findByOrderNumber_whenGivenBlankString_returnsEmpty() {
        orderRepository.save(new Order("ORD-6", "alice@example.com", Instant.now()));

        Optional<Order> found = orderRepository.findByOrderNumber("");

        assertThat(found).isEmpty();
    }

    @Test
    void save_staleCopy_isRejectedInsteadOfOverwritingANewerChange() {
        // A race between two requests, replayed in slow motion on one thread. Both "requests" read
        // the same version of the order, the first saves, then the second saves its stale copy.
        Long id = entityManager.persistFlushFind(new Order("ORD-LOCK", "alice@example.com", Instant.now())).getId();
        entityManager.clear();

        Order seenByShip = orderRepository.findById(id).orElseThrow();
        entityManager.detach(seenByShip);
        Order seenByCancel = orderRepository.findById(id).orElseThrow();
        entityManager.detach(seenByCancel);

        seenByCancel.setStatus(OrderStatus.CANCELLED);
        orderRepository.saveAndFlush(seenByCancel);

        seenByShip.setStatus(OrderStatus.SHIPPED);
        // Without @Version this would succeed, and the cancellation would vanish without a trace.
        assertThatThrownBy(() -> orderRepository.saveAndFlush(seenByShip))
                .isInstanceOf(ObjectOptimisticLockingFailureException.class);

        entityManager.clear();
        assertThat(orderRepository.findById(id).orElseThrow().getStatus()).isEqualTo(OrderStatus.CANCELLED);
    }

    @Test
    void save_duplicateOrderNumber_throwsDataIntegrityViolationException() {
        orderRepository.saveAndFlush(new Order("ORD-DUP", "alice@example.com", Instant.now()));
        Order duplicate = new Order("ORD-DUP", "bob@example.com", Instant.now());

        assertThatThrownBy(() -> orderRepository.saveAndFlush(duplicate))
                .isInstanceOf(DataIntegrityViolationException.class);
    }

    @Test
    void save_missingRequiredField_throwsDataIntegrityViolationException() {
        // customerEmail is nullable = false at the column level; nothing in Java stops you from
        // passing null, so this documents that the *database* is what actually enforces it here
        // — there is no Bean Validation (@NotNull) layer yet (that belongs in the service, §9).
        Order missingEmail = new Order("ORD-7", null, Instant.now());

        assertThatThrownBy(() -> orderRepository.saveAndFlush(missingEmail))
                .isInstanceOf(DataIntegrityViolationException.class);
    }

    @Test
    void save_cascadesItemsWithTheOrder() {
        Order order = new Order("ORD-2", "alice@example.com", Instant.now());
        order.addItem(new OrderItem("Widget", 2, new BigDecimal("9.99")));
        order.addItem(new OrderItem("Gadget", 1, new BigDecimal("19.99")));

        Order saved = orderRepository.saveAndFlush(order);
        entityManager.clear();

        Order reloaded = orderRepository.findById(saved.getId()).orElseThrow();
        assertThat(reloaded.getItems())
                .hasSize(2)
                .extracting(OrderItem::getProductName)
                .containsExactlyInAnyOrder("Widget", "Gadget");
    }

    @Test
    void removeItem_orphanRemoval_deletesItFromTheDatabase() {
        Order order = new Order("ORD-3", "alice@example.com", Instant.now());
        OrderItem toRemove = new OrderItem("Widget", 2, new BigDecimal("9.99"));
        order.addItem(toRemove);
        order.addItem(new OrderItem("Gadget", 1, new BigDecimal("19.99")));
        orderRepository.saveAndFlush(order);

        order.removeItem(toRemove);
        orderRepository.saveAndFlush(order);
        entityManager.clear();

        Order reloaded = orderRepository.findById(order.getId()).orElseThrow();
        assertThat(reloaded.getItems())
                .extracting(OrderItem::getProductName)
                .containsExactly("Gadget");
    }

    @Test
    void deleteOrder_cascadesDeleteOfItsItems() {
        // Different from orphan removal above: this is CascadeType.ALL propagating a delete of
        // the parent all the way down, not a change to the in-memory items collection.
        Order order = new Order("ORD-4", "alice@example.com", Instant.now());
        order.addItem(new OrderItem("Widget", 1, new BigDecimal("5.00")));
        Order saved = orderRepository.saveAndFlush(order);
        Long orderId = saved.getId();

        orderRepository.delete(saved);
        entityManager.flush();

        assertThat(orderRepository.findById(orderId)).isEmpty();
        Long remainingItems = entityManager.getEntityManager()
                .createQuery("select count(i) from OrderItem i where i.order.id = :orderId", Long.class)
                .setParameter("orderId", orderId)
                .getSingleResult();
        assertThat(remainingItems).isZero();
    }

    @Test
    void save_roundTripsInstantAtMicrosecondPrecision() {
        // Postgres "timestamp" stores microsecond precision; Instant.now() can carry nanoseconds.
        // Truncate before persisting if exact round-trip equality matters later on.
        Instant original = Instant.now().truncatedTo(ChronoUnit.MICROS);

        Order saved = orderRepository.saveAndFlush(new Order("ORD-8", "alice@example.com", original));
        entityManager.clear();

        Order reloaded = orderRepository.findById(saved.getId()).orElseThrow();
        assertThat(reloaded.getCreatedAt()).isEqualTo(original);
    }

    @Test
    void save_roundTripsItemUnitPriceByValueNotScale() {
        // BigDecimal.equals() is scale-sensitive (12.50 != 12.5000); isEqualByComparingTo isn't.
        // Worth knowing which one you're asserting with before trusting a "green" money test.
        Order order = new Order("ORD-9", "alice@example.com", Instant.now());
        order.addItem(new OrderItem("Widget", 3, new BigDecimal("12.50")));
        Order saved = orderRepository.saveAndFlush(order);
        entityManager.clear();

        Order reloaded = orderRepository.findById(saved.getId()).orElseThrow();
        assertThat(reloaded.getItems().get(0).getUnitPrice()).isEqualByComparingTo("12.50");
    }

    @Test
    void findByStatus_whenNoOrdersMatch_returnsEmptyPage() {
        orderRepository.save(new Order("ORD-5", "alice@example.com", Instant.now()));

        Page<Order> page = orderRepository.findByStatus(OrderStatus.CANCELLED, PageRequest.of(0, 10));

        assertThat(page.getTotalElements()).isZero();
        assertThat(page.getContent()).isEmpty();
    }

    @Test
    void findByStatus_supportsPagingAndSorting() {
        for (int i = 0; i < 5; i++) {
            orderRepository.save(new Order("ORD-PAGE-" + i, "alice@example.com",
                    Instant.now().plus(i, ChronoUnit.SECONDS)));
        }

        Page<Order> firstPage = orderRepository.findByStatus(OrderStatus.CREATED,
                PageRequest.of(0, 2, Sort.by(Sort.Direction.ASC, "orderNumber")));

        assertThat(firstPage.getTotalElements()).isEqualTo(5);
        assertThat(firstPage.getContent())
                .extracting(Order::getOrderNumber)
                .containsExactly("ORD-PAGE-0", "ORD-PAGE-1");
    }

    @Test
    void findRecentOrdersForCustomer_ordersByCreatedAtDescending() {
        Instant now = Instant.now();
        orderRepository.save(new Order("ORD-OLD", "alice@example.com", now.minus(1, ChronoUnit.HOURS)));
        orderRepository.save(new Order("ORD-NEW", "alice@example.com", now));
        orderRepository.save(new Order("ORD-OTHER-CUSTOMER", "bob@example.com", now));

        List<Order> recent = orderRepository.findRecentOrdersForCustomer("alice@example.com");

        assertThat(recent)
                .extracting(Order::getOrderNumber)
                .containsExactly("ORD-NEW", "ORD-OLD");
    }
}
